---
- hosts: smartbox
  vars:
    # ansible_python_interprete: "/usr/bin/python3"
    smartbox_home: "/smartbox"
  remote_user: root
  
  tasks:
  - name: Install rkt
    yum:
      name: rkt
      state: present


  - name: Set environment variables
    copy:
      content: "export SMARTBOX_HOME=\"{{ smartbox_home }}\""
      dest: /etc/profile.d/smartbox.sh
  
  - name: Create flightcontrol directory
    file: path="{{ smartbox_home }}/flightcontrol" state=directory
    
  - name: Create webiu directory
    file: path="{{ smartbox_home }}/webiu" state=directory

  - name: Copy flightcontrol
    copy:
      src: "../flightcontrol/"
      dest: "{{ smartbox_home }}/flightcontrol"
      owner: root

  - name: Copy webui
    copy:
      src: "../webui/"
      dest: "{{ smartbox_home }}/webiu"
      owner: root

  - name: Copy service unit file
    copy: src="../build/smartbox.service" dest="/etc/systemd/system/smartbox.service"

  - name: (re)start smartbox service
    service: name=smartbox state=restarted