Vagrant.configure(2) do |config|
  config.vm.box = "fedora/25-cloud-base"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.define :smartbox do |smartbox|
  end
  config.vm.provision  "ansible" do |ansible|
    ansible.playbook = "smartbox.yml"
    ansible.sudo = true
  end

#  # another named provision strategy
#  config.vm.provision "main", type: "ansible" do |ansible|
#    ansible.playbook = "smartbox.yml"
#  end
end

