---
- hosts: all
  become: yes
  become_user: root
  vars:
    ansible_python_interprete: "/usr/bin/python2"
  
  tasks:
  - name: Install rkt
    become: yes
    package:
      name: rkt
      state: present
    when: ansible_distribution != 'Debian' and ansible_distribution != 'Ubuntu'

  - name: Install rkt (Debian/Ubuntu)
    become: yes
    script: install_rkt_debian.sh
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: Install libnss-mdns for zeroconf/mDNS hostname
    become: yes
    package:
      name: libnss-mdns
      state: present
  
  - name: Create flightcontrol directory
    become: yes
    file: path="/etc/smartbox/flightcontrol" state=directory
    
  - name: Create webiu directory
    become: yes
    file: path="/etc/smartbox/webiu" state=directory

  - name: Copy flightcontrol container image
    become: yes
    copy:
      src: "images/flightcontrol.aci"
      dest: "/etc/smartbox/flightcontrol.aci"
      owner: root

  - name: Copy webui container image
    become: yes
    copy:
      src: "images/webui.aci"
      dest: "/etc/smartbox/webui.aci"
      owner: root

  - name: Copy flightcontrol code
    become: yes
    copy:
      src: "../flightcontrol/"
      dest: "/etc/smartbox/flightcontrol"
      owner: root

  - name: Copy webui code
    become: yes
    copy:
      src: "../webui/"
      dest: "/etc/smartbox/webui"
      owner: root
  
  - name: Copy common code into flightcontrol
    become: yes
    copy:
      src: "../common/"
      dest: "/etc/smartbox/flightcontrol/common"
      owner: root

  - name: Copy common code into webui
    become: yes
    copy:
      src: "../common/"
      dest: "/etc/smartbox/webui/common"
      owner: root

  - name: Copy service unit file
    become: yes
    copy: 
      src: "smartbox.internal.flightcontrol.service"
      dest: "/etc/systemd/system/smartbox.internal.flightcontrol.service"

  - name: systemd daemon-reload
    systemd: daemon_reload=yes

  - name: (re)start smartbox service
    become: yes
    service: name=smartbox.internal.flightcontrol state=restarted