Vagrant.configure(2) do |config|
  #Vagrant::DEFAULT_SERVER_URL.replace('https://vagrantcloud.com')
  config.ssh.insert_key = false
  config.ssh.password = false
  config.vm.box = "debian/jessie64"
  config.vm.network "public_network"
  config.vm.define :smartbox do |smartbox|
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "smartboxinstall.yml"
    ansible.sudo = true
  end
end
